name: Generate GitHub Metrics

on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger from Actions tab
  workflow_dispatch:
  
  # Run on push to main/master branch
  push:
    branches: [ "main", "master" ]
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: yazzy01
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Casablanca
          
          # Display achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_display: compact   # Use compact display
          
          # Add language activity
          plugin_languages: yes
          plugin_languages_colors: github        # Use GitHub's colors
          plugin_languages_limit: 8              # Limit to 8 languages
          
          # Add coding habits
          plugin_habits: yes
          plugin_habits_days: 14                 # Keep only last 14 days
          plugin_habits_facts: yes               # Display facts section
          plugin_habits_charts: yes              # Display charts section
          
          # Add recent activity
          plugin_activity: yes
          plugin_activity_limit: 5               # Limit to 5 events
          plugin_activity_load: 300              # Load up to 300 events
          plugin_activity_days: 14               # Keep only last 14 days
          plugin_activity_filter: all            # Show all activity types
